services:
  postgres:
    image: postgres:16.3
    container_name: Finances_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminFinance.
      POSTGRES_DB: FinanceDatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

volumes:
  postgres_data:

networks:
  postgres-compose-network:
    driver: bridge
